import type { Metadata } from "next";
import { Lemon, Righteous, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });
export const lemon = Lemon({ subsets: ["latin"], weight: ["400"] });

// export poppinss = Poppins({subsets: ['latin'],weight:['400']})

export const righteous = Righteous({ subsets: ["latin"], weight: ["400"] });
export const metadata: Metadata = {
  title: "4 Beach Rentals | At The Beach 4 You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
